# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "rails_crons", :force => true do |t|
    t.column "command", :text
    t.column "start", :integer
    t.column "finish", :integer
    t.column "every", :integer
    t.column "concurrent", :boolean
  end

  create_table "recordings", :force => true do |t|
    t.column "title", :string
    t.column "starttime", :datetime
    t.column "duration", :integer
    t.column "station_id", :integer
    t.column "recorder", :text
    t.column "state", :string
  end

  create_table "stations", :force => true do |t|
    t.column "name", :string
    t.column "logo", :string
    t.column "stream_url", :string
    t.column "epg_url", :string
  end

end
